main: me.deceptions.commissary.Main
name: PrisonCommissary
version: 1.5
author: FXA
description: A cool and inventive commissary plugin for the best of prison servers!
website: https://deceptions.me
softdepend: [PlaceholderAPI,MVdWPlaceholderAPI]

commands:
  commissary:
    description: Shows the help menu for commissary!
  points:
    description: Shows the help menu for points!
  addpoints:
    description: Console command for adding points to a player!
  tickets:
    description: Allows tickets to be used in the plugin!

permissions:
  commissary.admin:
    description: Allows you to use /commissary commands.
  points.admin:
    description: Allows you to use any commands after /points.
  points.see:
    description: Allows you to use /points to see how many you have.
  points.pay:
    description: Allows you to use /points pay.